### ISSUE TITLE
Unable to delete nodes in Project map when using Godot 3.5.rc5

### ISSUE THREAD

**Issue by xylr117z4** [Yogoda/Project-Map#6]
You may already be aware of the issue, 
I searched around but I didn't see another post about it.
Feel free to close this issue if 3.5 isn't a concern yet. 
This is working in Godot 3.4.4.

I've been moving my code to 3.5.rc5 as I need features from 3.5 to complete my project. 
Project map seems to work perfectly fine except I can't delete nodes.

When I press delete the output console gives the error "core/object.cpp:1242 - Error calling method from signal 'delete_nodes_request': 'GraphEdit(project_map.gd)::_on_GraphEdit_delete_nodes_request': Method expected 0 arguments, but called with 1.."

Steps to repro:

Using Godot 3.5.rc5 (assuming this will be an issue in 3.5)
1. Create new project, 
2. add the plugin from a fresh download of ProjectMap V1.3.
3. Attempt to delete the initial comment or any node you add. 

![image](https://user-images.githubusercontent.com/639114/176808644-fb238744-fc6e-42d0-b1d6-b6acac966c27.png)

**Comment by xylr117z4** [comment]
It appears the issue is that in godot 3.5 they changed the delete_nodes_request signal to take an array of nodes. 

To fix this I just needed to add an input variable.
On line 219 of project_map.gd "func _on_GraphEdit_delete_nodes_request(array):"
After this deleting works just fine after saving, closing and reopening godot 3.5.rc5. 

But that will likely break 3.4.

**Comment by Yogoda** [comment]
Thank you for the nice report and fix :)

I committed the fix on Github.
